sudo: false
dist: trusty
addons:
  postgresql: 9.5

before_script:
  - psql -c 'create database postgresql_audit_test;' -U postgres

language: python

matrix:
  include:
  - python: 2.7
    env:
      - TOXENV='py-sqla{0.9,1.0,1.1}'
  - python: 3.3
    env:
      - TOXENV='py-sqla{0.9,1.0,1.1}'
  - python: 3.4
    env:
      - TOXENV='py-sqla{0.9,1.0,1.1}'
  - python: 3.5
    env:
      - TOXENV='py-sqla{0.9,1.0,1.1}'
  - python: 3.5
    env:
      - TOXENV='lint'

install:
  - pip install tox

script:
  - tox
